<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="Hangfire" Version="1.8.18" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.18" />
		<PackageReference Include="MediatR" Version="12.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.15" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="System.Linq" Version="4.3.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="CQRS\Notification\Orchestrators\" />
		<Folder Include="CQRS\Notification\Queries\" />
		<Folder Include="CQRS\Report\Orchestrators\" />
		<Folder Include="CQRS\Report\Queries\" />
		<Folder Include="CQRS\Warehouse\Orchestrators\" />
		<Folder Include="CQRS\ArchivedInventoryTransaction\Orchestrators\" />
		<Folder Include="CQRS\ArchivedInventoryTransaction\Queries\" />
	</ItemGroup>

</Project>
